# Generated by Django 6.0.7 on 2026-07-09 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_ensure_store_table'),
        ('users', '0004_ensure_recentlyviewed_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyviewed',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_by', to='catalog.product'),
        ),
    ]
