# Generated by Django 6.0.7 on 2026-07-13 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        ('users', '0005_alter_recentlyviewed_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_role',
            field=models.ForeignKey(blank=True, help_text='Role assigned to staff users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='admin_dashboard.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=10),
        ),
    ]
