# Generated by Django 6.0.7 on 2026-07-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('view_dashboard', 'View Dashboard'), ('view_products', 'View Products'), ('add_products', 'Add Products'), ('edit_products', 'Edit Products'), ('delete_products', 'Delete Products'), ('view_categories', 'View Categories'), ('add_categories', 'Add Categories'), ('edit_categories', 'Edit Categories'), ('delete_categories', 'Delete Categories'), ('view_orders', 'View Orders'), ('edit_orders', 'Edit Orders'), ('delete_orders', 'Delete Orders'), ('view_reviews', 'View Reviews'), ('edit_reviews', 'Edit Reviews'), ('delete_reviews', 'Delete Reviews'), ('view_users', 'View Users'), ('add_staff', 'Add Staff'), ('edit_staff', 'Edit Staff'), ('delete_staff', 'Delete Staff'), ('manage_roles', 'Manage Roles')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='admin_dashboard.rolepermission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
    ]
