# Generated by Django 6.0.7 on 2026-07-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='code',
            field=models.CharField(choices=[('view_dashboard', 'View Dashboard'), ('view_products', 'View Products'), ('add_products', 'Add Products'), ('edit_products', 'Edit Products'), ('delete_products', 'Delete Products'), ('manage_featured', 'Manage Featured Products'), ('view_categories', 'View Categories'), ('add_categories', 'Add Categories'), ('edit_categories', 'Edit Categories'), ('delete_categories', 'Delete Categories'), ('view_orders', 'View Orders'), ('edit_orders', 'Edit Orders'), ('delete_orders', 'Delete Orders'), ('update_order_status', 'Update Order Status'), ('view_reviews', 'View Reviews'), ('edit_reviews', 'Edit Reviews'), ('delete_reviews', 'Delete Reviews'), ('approve_reviews', 'Approve Reviews'), ('view_likes', 'View Likes'), ('delete_likes', 'Delete Likes'), ('view_users', 'View Users'), ('add_staff', 'Add Staff'), ('edit_staff', 'Edit Staff'), ('delete_staff', 'Delete Staff'), ('activate_users', 'Activate/Deactivate Users'), ('view_roles', 'View Roles'), ('add_roles', 'Add Roles'), ('edit_roles', 'Edit Roles'), ('delete_roles', 'Delete Roles'), ('manage_role_permissions', 'Manage Role Permissions')], max_length=50, unique=True),
        ),
    ]
