# Generated by Django 6.0.7 on 2026-07-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_delete_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sierra Luxe', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('smooth_shipping', models.BooleanField(default=True, help_text='Has a history of shipping on time with tracking')),
                ('speedy_replies', models.BooleanField(default=True, help_text='Has a history of replying to messages quickly')),
                ('average_rating', models.DecimalField(decimal_places=2, default=4.8, help_text='Average review rating', max_digits=3)),
                ('total_reviews', models.IntegerField(default=0, help_text='Total number of reviews')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
    ]
