# Generated by Django 6.0.7 on 2026-07-09 19:43

import cloudinary.models
from django.db import migrations


def preserve_existing_images(apps, schema_editor):
    """Preserve existing image URLs when converting to CloudinaryField"""
    Product = apps.get_model('catalog', 'Product')
    ProductImage = apps.get_model('catalog', 'ProductImage')
    
    # Preserve existing product main_image and video URLs
    for product in Product.objects.all():
        if product.main_image:
            # CloudinaryField will accept the existing URL string
            original_image = product.main_image
            product.main_image = original_image
            product.save(update_fields=['main_image'])
        
        if product.video:
            original_video = product.video
            product.video = original_video
            product.save(update_fields=['video'])
    
    # Preserve existing product image URLs
    for product_image in ProductImage.objects.all():
        if product_image.image:
            original_image = product_image.image
            product_image.image = original_image
            product_image.save(update_fields=['image'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_videos'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_images'),
        ),
        migrations.RunPython(preserve_existing_images, migrations.RunPython.noop),
    ]
