# Generated by Django 6.0.7 on 2026-07-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_clear_existing_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, help_text='Cloudinary video URL', null=True),
        ),
    ]
