# Generated by Django 6.0.7 on 2026-07-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_ensure_store_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_navbar',
            field=models.BooleanField(default=True, help_text='Display in navbar category menu'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(default=True, help_text='Display in homepage Shop by Category section'),
        ),
    ]
