# Generated by Django 6.0.7 on 2026-07-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='saved_for_later',
            field=models.BooleanField(default=False),
        ),
    ]
